### ISSUE TITLE
Example related migration in readme file

### ISSUE THREAD

**Issue by tskupinski** [pienkowb/active_record-events#1]
It would be nice to have example migration required to use model event presented in readme file.

**Comment by pienkowb** [comment]
The example should also cover the case when there's no object defined (which is more common). 

Ideally, there would be a Rails generator responsible for generating a migration and declaring an event in the corresponding model, which would be invoked in the following way:

```ruby
rails generate active_record:event task complete
```

The name of an object would need to be passed as a parameter.

**Comment by pienkowb** [comment]
Duplicate of #2
