### ISSUE TITLE
Mapping for validation errors

### ISSUE THREAD

**Issue by mpkhr** [pienkowb/active_record-events#21]
Hi guys,

small idea to improve the gem: It would be great to have a mapping for validation errors, as to the user those fields remain a boolean.

Use case is: there is some business logic behind a field. If the user runs in such validation errors, the validation errors shouldn't be added to `:completed_at`, but rather to `:completed`, which is what is then used in the forms.

Can all be done manually of course, but I think this would be a nice addition to connect the pieces between forms, validations and the "behind the scenes" timestamp field.

Thanks!

**Comment by pienkowb** [comment]
Hey, thanks for reaching out!

Could you give an example of such a validation? The gem itself does not add any validations around timestamp fields automatically.
