### ISSUE TITLE
Handle the date field type

### ISSUE THREAD

**Issue by pienkowb** [pienkowb/active_record-events#6]
For now, the gem supports only `datetime` fields, which by convention end with `_at` (e.g. `delivered_at`). The task is to add support for `date` fields, which by contrast have the `_on` suffix (e.g. `delivered_on`).

The behaviour should be configurable using the `field_type` option:
```ruby
has_event :deliver, field_type: :date
```

**Comment by tskupinski** [comment]
I would like to look into this.
